### ISSUE TITLE
Does not register itself as a language with file extensions

### ISSUE THREAD

**Issue by basarat** [Microsoft/monaco-css#3] opened 2016-06-30 22:51 UTC
In various other packages I see a call to `monaco.languages.register({` e.g. https://github.com/Microsoft/monaco-json/blob/7e50cccbb2e8248ffbdbae54ca440f2714dbc945/src/monaco.contribution.ts#L69-L74 

```ts
monaco.languages.register({
	id: 'json',
	extensions: ['.json', '.bowerrc', '.jshintrc', '.jscsrc', '.eslintrc', '.babelrc'],
	aliases: ['JSON', 'json'],
	mimetypes: ['application/json'],
});
```

However this is not happening in monaco-css contribution : https://github.com/Microsoft/monaco-css/blob/a95094a5990b443cead16f31c374a3c8c2966bfe/src/monaco.contribution.ts 

I just tried pulling this into alm (refs https://github.com/alm-tools/alm/issues/138) and even though the contribution file is loaded nothing happens. Did this package miss something? 

If not then Its on me to figure out alm issues (refs https://github.com/alm-tools/alm/pull/139) :) :rose:

**Comment by alexandrudima** [comment] 2016-07-13 11:54
@aeschli How does this work? Where are the language registrations?

**Comment by alexandrudima** [comment] 2016-07-13 11:55
Oh now I remember. @basarat https://github.com/Microsoft/monaco-languages/blob/master/src/monaco.contribution.ts#L193

* monaco-languages supplies basic coloring support for css, less and sass
* this repo provides advanced language features for those languages

**Comment by aeschli** [comment] 2016-07-13 15:08
duplicate of #4. Language definition and tokenizer are in the monaco-languages.

**Closed by aeschli** 2016-07-13 15:08 UTC
